@startwbs
* 安宠居APP项目
** 项目管理
*** 项目启动
*** 项目开工会议
*** 项目计划
**** 范围计划
**** 任务/活动定义
**** 项目进度表
**** 工作分解结构
**** 质量计划
*** 项目沟通
*** 项目团队建议
*** 项目风险监控
*** 项目收尾总结
** 系统定义
*** 定义目标
**** 系统总体目标
**** 确定各子目标
**** 明确关键事件
*** 定义需求
**** 获得既定需求
**** 定义新需求
**** 设计测试用例
*** 选择系统开发方法
*** 审批
** 系统设计
*** 系统功能
**** 定义系统接口
**** IO设计
**** 系统审计/控制
**** 功能计划确认
*** 系统技术
**** 模块说明
**** 系统流程
**** 数据转换
**** 集成测试计划
**** 审批
** 系统实现
*** 程序编码
**** 编码
**** 单元测试
*** JCL
**** JCL编码
**** 单元测试
*** 文档编写
*** 集成测试
**** 测试方案定制
**** 测试
**** 编写测试报告
** 系统交付
*** 系统安装
*** 培训
**** 最终用户培训
**** 系统管理员培训
*** 试运行
*** 系统切换
**** 却换方案确定
**** 数据转换
**** 切换到成产系统
*** 验收
** 系统运行
*** 日常操作
*** 运行检查
**** 运行检查计划
**** 检查运行状况
*** 系统审计
@endwbs